version: "2"

services:

  app:
    image: zzrot/alpine-caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - API_ADDRESS
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./app/serve:/var/www/html
      - ./.caddy:/root/.caddy
    links:
      - api

  api:
    build: ./api
    scale: 2
    restart: always
    volumes:
      - ./api:/app
    links:
      - redis
      - mongo
    depends_on:
      - redis

  mongo:
    build: ./docker/mongo
    restart: always
    environment:
      - MONGODB_ADMIN_USER
      - MONGODB_ADMIN_PASS
      - MONGODB_APPLICATION_DATABASE
      - MONGODB_APPLICATION_USER
      - MONGODB_APPLICATION_PASS
    volumes_from:
      - mongodata
    ports:
      - "27018:27017"
    command: --auth

  mongoui:
    image: twnel/mongo-express
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD
      - ME_CONFIG_MONGODB_ENABLE_ADMIN
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
    ports:
      - "8081:8081"
    links:
      - mongo

  mongodata:
    image: tianon/true
    volumes:
      - /data/db

  mongobackup:
    build: ./utilities/backup
    restart: always
    links:
      - mongo
    ports:
      - 27017
    environment:
      - MONGO_HOST
      - MONGO_DB
      - MONGO_PORT
      - S3_BUCKET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      #- DATE_FORMAT
      #- FILE_PREFIX
      - MONGODB_APPLICATION_USER
      - MONGODB_APPLICATION_PASS
      - BACKUP_TIME=18:02

  redis:
    image: redis:4.0.5-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data: